### ISSUE TITLE
Missing module/svelte entry point in package.json?

### ISSUE THREAD

**Issue by janosh** [micha-lmxt/svelte-window#6]
Trying to import `svelte-window` in a SvelteKit project throws

```txt
[vite] Error when evaluating SSR module repo/site/src/routes/index.svelte:
repo/node_modules/svelte-window/src/index.js:5
export { default as VariableSizeGrid } from './VariableSizeGrid';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1038:15)
    at Module._compile (node:internal/modules/cjs/loader:1072:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at nodeRequire (repo/node_modules/vite/dist/node/chunks/dep-2c03f3f9.js:69080:17)
    at ssrImport (repo/node_modules/vite/dist/node/chunks/dep-2c03f3f9.js:69038:20)
```

Perhaps part of the problem is missing `module` field in `package.json`? Adding

```js
    vite: {
      ssr: { noExternal: [`svelte-window`] },
    },
```

to `svelte.config.js` didn't help.

**Comment by micha-lmxt** [comment]
Hi, svelte-window is using DOM-element methods to measure what is currently visible on screen. By that it disqualifies itself as an SSR component. If you wrap it in a `{#if mounted}` clause, where `mounted` is set to true in the `onMount` lifecycle, there should be a good chance it works.

Let me know, if you can get it to run. Thank you!

**Comment by janosh** [comment]
Thanks for the quick reply!

I don't think accessing `window` is the problem here. Maybe it will turn into a problem later on. But in any case, it's still giving the same syntax error with this code:

```
<script>
  import { onMount } from 'svelte'
  import { FixedSizeGrid as Grid, styleString as sty } from 'svelte-window'

  let grid
  let mounted = false
  onMount(() => (mounted = true))

  const click = () => {
    if (grid) {
      grid.scrollToItem({
        align: `start`,
        columnIndex: 150,
        rowIndex: 300,
      })
    }
  }
</script>

{#if mounted}
  <Grid
    bind:this={grid}
    columnCount={1000}
    columnWidth={100}
    height={150}
    rowCount={1000}
    rowHeight={35}
    width={300}
    useIsScrolling
    let:items>
    {#each items as it (it.key)}
      <div style={sty(it.style)}>
        {it.isScrolling ? `Scrolling` : `Row ${it.rowIndex} - Col ${it.columnIndex}`}
      </div>
    {/each}
  </Grid>

  <button on:click={click}> To row 300, column 150 </button>
{/if}
```

You can repro this yourself if you like with the default SvelteKit starter by running

```
npm init svelte@next svelte-window+kit
cd svelte-window+kit
npm i
npm i -D svelte-window
npm run dev
```

and then pasting the above code into `src/routes/index.svelte`.

**Comment by micha-lmxt** [comment]
Found some time to look into it. Since SvelteKit is only beta, you can never be sure if something should work with it or not. 

Apparently, for SvelteKit components aren't classes but proxies, so, I can't inherit. I worked around differently and with a fresh install today it went well.

I've also updated the readme. 

Hope that fixes it

**Comment by janosh** [comment]
That's great! Could you share your code?

**Comment by micha-lmxt** [comment]
Sure, here it is: https://github.com/micha-lmxt/svelte-window-kit

There are no big changes to the default starter package.

**Comment by janosh** [comment]
Thanks! Tried your repo and it worked immediately. Still couldn't get mine to work though until I added

```js
vite: {
  ssr: { noExternal: [`svelte-window`] },
},
```

to `svelte.config.js`. Not sure why? Maybe a problem with my setup (e.g. using `yarn` instead of `npm`).

I have a question that maybe belongs in a new issue: Is it possible to import components dynamically into a `svelte-window` grid? Those usually need to be awaited but not sure how to do that inside the grid `each` loop? Maybe this explains what I'm trying to do.

```svelte
<Grid
  bind:this={grid}
  {columnCount}
  columnWidth={150}
  height={250}
  rowCount={1000}
  rowHeight={35}
  {width}
  let:items>
  {#each items as it (it.key)}
    <div style={sty(it.style)}>
      <svelte:component this={import(componentPaths[it.rowIndex * columnCount + it.columnIndex]).default} />
    </div>
  {/each}
</Grid>
```

**Comment by micha-lmxt** [comment]
Sorry, I was a bit busy with Svelte-Motion☺️. I think there are no version numbers in SvelteKit yet, even though there is a lot development going on. Maybe you get a newer version when you start a fresh project.

If only the each loop is a problem you can refactor the code into a separate component. I try to set up a REPL this evening.

**Comment by micha-lmxt** [comment]
starting from: https://svelte.dev/repl/16b375da9b39417dae837b5006799cb4?version=3.25.0
to this: https://svelte.dev/repl/ec2587828194443296d21c5d48847ad6?version=3.25.0

**Comment by janosh** [comment]
Very cool! All working now. Thanks for making `svelte-window`!

I think the readme would benefit from a section explaining the differences between `VariableSizeGridSSR` and `FixedSizeGridSSR` and when to use which.
